### ISSUE TITLE
[1.20.4] Item duping

### ISSUE THREAD

**Issue by perrilol** [JamCoreModding/utility-belt#46] opened 2024-06-03 23:09 UTC
![Снимок экрана 2024-06-04 020711](https://github.com/JamCoreModding/utility-belt/assets/171631634/9e2ff82e-0998-4678-9c19-a008a0ddde3f)

Discovered on Fabric
When you left click on the belt while it eqiped, it duplicates an item you have in first slot

**Comment by Jamalam360** [comment] 2024-06-04 12:19
Duplicate of #45, thanks

**Closed by Jamalam360** 2024-06-04 12:19 UTC
