### ISSUE TITLE
Crash from tutorial-lib, probably an incompat. 

### ISSUE THREAD

**Issue by purejosh** [JamCoreModding/utility-belt#27] opened 2023-06-20 22:47 UTC
[latest (13).log](https://github.com/JamCoreModding/utility-belt/files/11808444/latest.13.log)

This is probably an incompatibility somewhere, since our modpack is quite big. Lmk what other info you'll need, but it should all be in the log here.

**Comment by Jamalam360** [comment] 2023-06-21 05:26
Looks like a silly mistake on my part, will fix today

**Comment by booa12** [comment] 2023-06-21 09:07
i have the same issue

**Comment by booa12** [comment] 2023-06-21 09:08
i know its utility belts problem

**Comment by booa12** [comment] 2023-06-21 09:11
i have the latest version and crash

**Comment by booa12** [comment] 2023-06-21 09:14
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'tutorial-lib'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.21.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.2-loader.0.14.21-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents in environment type SERVER
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at io.github.jamalam360.tutorial.lib.TutorialLib.onInitialize(TutorialLib.java:61) ~[tutorial-lib-1.1.1+1.19.2-a9d08e204676b104.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
        ... 8 more

**Comment by booa12** [comment] 2023-06-21 09:25
also its on the server

**Comment by Jamalam360** [comment] 2023-06-21 09:34
Are you sure you're on V1.3.1, I just fixed this issue

**Comment by booa12** [comment] 2023-06-21 09:35
Yes

**Comment by booa12** [comment] 2023-06-21 09:35
But its on the server

**Comment by booa12** [comment] 2023-06-21 09:40
C:\Users\Nooa\Desktop\testing\Fabric>java -Xmx6G -jar fabric-server-mc.1.19.2-loader.0.14.21-launcher.0.11.2.jar nogui
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[12:39:57] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.21
[12:39:57] [ForkJoinPool-1-worker-3/WARN]: Mod io_netty_netty-codec-http uses the version 4.1.77.Final which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'Final'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[12:39:57] [ForkJoinPool-1-worker-1/WARN]: Mod flywheel uses the version 0.6.8.a-5 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'a'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[12:39:57] [ForkJoinPool-1-worker-4/WARN]: The mod "moreredlamps" contains invalid entries in its mod json:
- Unsupported root entry "client" at line 24 column 11
[12:39:57] [main/INFO]: Loading 128 mods:
        - animated_guns 1.2
        - automobility 0.4.1+1.19.2-fabric
           |-- advanced_runtime_resource_pack 0.6.2
           \-- jsonem 0.1.2+1.19
        - azurelib 1.0.23
           \-- com_eliotlash_mclib_mclib 20
        - badpackets 0.2.1
        - cardinal-components-item 5.0.2
        - carpet 1.4.84
        - carpet-extra 1.4.84
        - computercraft 1.101.2
           |-- io_netty_netty-codec-http 4.1.77.Final
           \-- org_squiddev_cobalt 0.5.5
        - create 0.5.1-b-build.1079+mc1.19.2
           |-- com_google_code_findbugs_jsr305 3.0.2
           |-- flywheel 0.6.8.a-5
           |-- forgeconfigapiport 4.2.9
           |    |-- com_electronwill_night-config_core 3.6.5
           |    \-- com_electronwill_night-config_toml 3.6.5
           |-- milk 1.0.51
           |    \-- dripstone_fluid_lib 2.0.1
           |-- porting_lib 2.1.1032+1.19.2
           |    |-- forge_tags 3.0
           |    |-- mm 2.3
           |    |-- porting_lib_accessors 2.1.1032+1.19.2
           |    |-- porting_lib_attributes 2.1.1032+1.19.2
           |    |-- porting_lib_base 2.1.1032+1.19.2
           |    |-- porting_lib_common 2.1.1032+1.19.2
           |    |-- porting_lib_constants 2.1.1032+1.19.2
           |    |-- porting_lib_entity 2.1.1032+1.19.2
           |    |-- porting_lib_extensions 2.1.1032+1.19.2
           |    |-- porting_lib_fake_players 2.1.1032+1.19.2
           |    |-- porting_lib_lazy_registration 2.1.1032+1.19.2
           |    |-- porting_lib_loot 2.1.1032+1.19.2
           |    |-- porting_lib_model_generators 2.1.1032+1.19.2
           |    |-- porting_lib_model_loader 2.1.1032+1.19.2
           |    |-- porting_lib_models 2.1.1032+1.19.2
           |    |-- porting_lib_networking 2.1.1032+1.19.2
           |    |-- porting_lib_obj_loader 2.1.1032+1.19.2
           |    |-- porting_lib_transfer 2.1.1032+1.19.2
           |    \-- serialization_hooks 0.3.26
           |-- reach-entity-attributes 2.3.0
           \-- registrate-fabric 1.1.58-MC1.19.2
        - extended_drawers 1.4.1+mc.1.19.2
           |-- graphlib 0.3.6+1.19.2
           \-- mconfig 1.2.0+mc.1.19-rc1
                |-- de_poiu_apron_apron 2.1.1
                \-- fabric-permissions-api-v0 0.1-SNAPSHOT
        - fabric-api 0.76.0+1.19.2
           |-- fabric-api-base 0.4.15+8f4e8eb390
           |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
           |-- fabric-biome-api-v1 9.1.1+16f1e31390
           |-- fabric-block-api-v1 1.0.2+e415d50e90
           |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
           |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
           |-- fabric-command-api-v1 1.2.16+f71b366f90
           |-- fabric-command-api-v2 2.2.1+413cbbc790
           |-- fabric-commands-v0 0.2.33+df3654b390
           |-- fabric-containers-v0 0.1.41+df3654b390
           |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
           |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
           |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
           |-- fabric-data-generation-api-v1 5.3.8+413cbbc790
           |-- fabric-dimensions-v1 2.1.35+0d0f210290
           |-- fabric-entity-events-v1 1.5.4+9244241690
           |-- fabric-events-interaction-v0 0.4.34+562bff6e90
           |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
           |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
           |-- fabric-item-api-v1 1.6.6+b7d1888890
           |-- fabric-item-groups-v0 0.3.39+9244241690
           |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
           |-- fabric-keybindings-v0 0.2.23+df3654b390
           |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
           |-- fabric-loot-api-v2 1.1.13+83a8659290
           |-- fabric-loot-tables-v1 1.1.16+9e7660c690
           |-- fabric-message-api-v1 5.0.7+93d8cb8290
           |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
           |-- fabric-models-v0 0.3.21+c6af733c90
           |-- fabric-networking-api-v1 1.2.11+10eb22f490
           |-- fabric-networking-v0 0.3.28+df3654b390
           |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
           |-- fabric-particles-v1 1.0.14+4d0d570390
           |-- fabric-recipe-api-v1 1.0.1+413cbbc790
           |-- fabric-registry-sync-v0 0.9.32+9244241690
           |-- fabric-renderer-api-v1 1.2.1+1adbf27790
           |-- fabric-renderer-indigo 0.8.0+1adbf27790
           |-- fabric-renderer-registries-v1 3.2.24+df3654b390
           |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
           |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
           |-- fabric-rendering-v0 1.1.27+df3654b390
           |-- fabric-rendering-v1 1.12.1+d8ef690890
           |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
           |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
           |-- fabric-screen-api-v1 1.0.32+4d0d570390
           |-- fabric-screen-handler-api-v1 1.3.7+1cc24b1b90
           |-- fabric-sound-api-v1 1.0.2+c4f28df590
           |-- fabric-textures-v0 1.0.24+aeb40ebe90
           |-- fabric-transfer-api-v1 2.1.6+413cbbc790
           \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
        - fabricloader 0.14.21
        - ferritecore 5.0.3
        - geckolib3 3.1.40
        - hwg 1.4.10
        - jamlib 0.6.0+1.19
        - java 17
        - jei 11.6.0.1015
        - krypton 0.2.1
           \-- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT
        - lithium 0.11.1
        - memoryleakfix 1.1.1
           \-- com_github_llamalad7_mixinextras 0.2.0-beta.8
        - minecraft 1.19.2
        - moreredlamps 0.0.2-1.19
        - securityforfabric 1.2.1-1.19.2
        - sit 1.19-20
        - smartbrainlib 1.9
        - smoothchunk 1.19.1-2.0
        - starlight 1.1.1+fabric.ae22326
        - trinkets 3.4.2
           |-- cardinal-components-base 5.0.0-beta.1
           \-- cardinal-components-entity 5.0.0-beta.1
        - utilitybelt 1.3.1+1.19.2
           \-- tutorial-lib 1.1.1+1.19.2
        - valkyrienskies 2.2.0-beta.2
           |-- cloth-config 6.3.81
           |    \-- cloth-basic-math 0.6.1
           \-- fabric-language-kotlin 1.8.5+kotlin.1.7.20
                |-- org_jetbrains_kotlin_kotlin-reflect 1.7.20
                |-- org_jetbrains_kotlin_kotlin-stdlib 1.7.20
                |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.20
                |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.20
                |-- org_jetbrains_kotlinx_atomicfu-jvm 0.18.4
                |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
                |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
                |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
                |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1
                |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1
                \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1
        - vs_eureka 1.2.0-beta.1
        - worldedit 7.2.12+6240-87f4ae1
        - wthit 5.16.2
        - xaerominimap 23.4.4
[12:39:58] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Nooa/Desktop/testing/Fabric/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[12:39:58] [main/INFO]: Compatibility level set to JAVA_17
[12:39:59] [main/INFO]: Loaded configuration file for Lithium: 114 options available, 4 override(s) found
[12:39:59] [main/WARN]: Reference map 'eureka-1192-fabric-refmap.json' for vs_eureka.mixins.json could not be read. If this is a development environment you can ignore this message
[12:40:00] [main/WARN]: Error loading class: net/minecraft/class_759 (java.lang.ClassNotFoundException: net/minecraft/class_759)
[12:40:00] [main/WARN]: @Mixin target net.minecraft.class_759 was not found hwg.mixins.json:HeldItemRendererMixin from mod hwg
[12:40:00] [main/WARN]: Force-disabling mixin 'ai.task.memory_change_counting.BrainMixin' as rule 'mixin.ai.task.memory_change_counting' (added by mods [smartbrainlib]) disables it and children
[12:40:00] [main/WARN]: Force-disabling mixin 'ai.task.memory_change_counting.TaskMixin' as rule 'mixin.ai.task.memory_change_counting' (added by mods [smartbrainlib]) disables it and children
[12:40:00] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[12:40:00] [main/WARN]: Force-enabling mixin 'block.hopper.worldedit_compat.WorldChunkMixin' as rule 'mixin.block.hopper.worldedit_compat' (added by mods [lithium-fabric]) enables it
[12:40:00] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
[12:40:01] [main/WARN]: Error loading class: net/minecraft/class_5616 (java.lang.ClassNotFoundException: net/minecraft/class_5616)
[12:40:01] [main/WARN]: @Mixin target net.minecraft.class_5616 was not found registrate-fabric.mixins.json:accessor.BlockEntityRenderersAccessor from mod registrate-fabric
[12:40:01] [main/WARN]: Error loading class: rbasamoyai/createbigcannons/munitions/AbstractCannonProjectile (java.lang.ClassNotFoundException: rbasamoyai/createbigcannons/munitions/AbstractCannonProjectile)
[12:40:01] [main/WARN]: Error loading class: rbasamoyai/createbigcannons/cannon_control/contraption/PitchOrientedContraptionEntity (java.lang.ClassNotFoundException: rbasamoyai/createbigcannons/cannon_control/contraption/PitchOrientedContraptionEntity)
[12:40:01] [main/WARN]: Error loading class: dev/ftb/mods/ftbchunks/data/ClaimedChunkManager (java.lang.ClassNotFoundException: dev/ftb/mods/ftbchunks/data/ClaimedChunkManager)
[12:40:01] [main/WARN]: Error loading class: com/simibubi/create/content/contraptions/components/structureMovement/AbstractContraptionEntity (java.lang.ClassNotFoundException: com/simibubi/create/content/contraptions/components/structureMovement/AbstractContraptionEntity)
[12:40:01] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/RenderSectionManager (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/RenderSectionManager)
[12:40:01] [main/WARN]: @Mixin target me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager was not found valkyrienskies-fabric.mixins.json:compat.sodium.MixinRenderSectionManager from mod valkyrienskies
[12:40:01] [main/WARN]: [carpet] detected, disabling UPDATE mixin com.sk89q.worldedit.fabric.mixin.MixinLevelChunkSetBlockHook
[12:40:01] [main/INFO]: [MemoryLeakFix] Will be applying 2 memory leak fixes!
[12:40:01] [main/INFO]: [MemoryLeakFix] Currently enabled memory leak fixes: [entityMemoriesLeak, biomeTemperatureLeak]
[12:40:01] [main/INFO]: I used the json to destroy the json
[12:40:05] [main/WARN]: Method overwrite conflict for getLanguage in worldedit-fabric.mixins.json:MixinServerPlayer from mod worldedit, previously written by carpet.mixins.ServerPlayer_scarpetEventMixin. Skipping method.
[12:40:11] [main/INFO]: Building unoptimized datafixer
[12:40:16] [main/INFO]: Registering ModItems for anim_guns
[12:40:16] [main/INFO]: Registering ModSounds for anim_guns
[12:40:19] [main/WARN]: Encountered duplicate API provider registration for item: minecraft:glass_bottle
[12:40:19] [main/WARN]: Encountered duplicate API provider registration for item: minecraft:bucket
[12:40:19] [main/WARN]: Encountered duplicate API provider registration for item: minecraft:bucket
[12:40:19] [main/WARN]: Encountered duplicate API provider registration for item: minecraft:glass_bottle
[12:40:20] [main/WARN]: Encountered duplicate API provider registration for item: minecraft:bucket
[12:40:21] [main/INFO]: Initializing GraphLib...
[12:40:21] [main/INFO]: GraphLib Initialized.
[12:40:21] [main/INFO]: Registered hwg config for auto-sync function
[12:40:21] [main/INFO]: [jamlib] Mod initialized!
[12:40:21] [main/INFO]: Compression will use Java, encryption will use Java
[12:40:21] [main/INFO]: Definitely not up to no good
[12:40:21] [main/INFO]: Hello security!
[12:40:21] [main/INFO]: Registering ModBlocks for securityforfabric
[12:40:21] [main/INFO]: Registering Mod Items for securityforfabric
[12:40:21] [main/INFO]: [jamlib] Registered config for utilitybelt
[12:40:21] [main/INFO]: [utilitybelt] Mod initialized!
[12:40:21] [main/ERROR]: No data fixer registered for valkyrienskies:ship_mounting_entity
[12:40:24] [main/INFO]: [STDOUT]: registering network handlers
[12:40:25] [main/ERROR]: No data fixer registered for ship_helm
[12:40:25] [main/ERROR]: No data fixer registered for engine
[12:40:26] [main/INFO]: Got request to register class com.sk89q.worldedit.fabric.FabricPlatform with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@687e0acb]
[12:40:26] [main/INFO]: WorldEdit for Fabric (version 7.2.12+6240-87f4ae1) is loaded
[12:40:27] [main/INFO]: [WTHIT] Registering plugin waila:core at mcp.mobius.waila.plugin.core.WailaCore
[12:40:27] [main/INFO]: [WTHIT] Registering plugin waila:vanilla at mcp.mobius.waila.plugin.vanilla.WailaVanilla
[12:40:27] [main/INFO]: [WTHIT] Plugin config reloaded
[12:40:27] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'tutorial-lib'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.21.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.2-loader.0.14.21-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents in environment type SERVER
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at io.github.jamalam360.tutorial.lib.TutorialLib.onInitialize(TutorialLib.java:61) ~[tutorial-lib-1.1.1+1.19.2-a9d08e204676b104.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
        ... 8 more

**Comment by booa12** [comment] 2023-06-21 09:41
there is full server log

**Comment by Jamalam360** [comment] 2023-06-21 09:47
Will be fixed soon

**Comment by booa12** [comment] 2023-06-21 09:48
ty pls sey it in the issue so i can see it

**Comment by Jamalam360** [comment] 2023-06-21 09:52
V1.3.2

**Comment by booa12** [comment] 2023-06-21 09:52
Aleredy?

**Comment by Jamalam360** [comment] 2023-06-21 09:54
Yes. It might not be visible on Curseforge yet, but it is on [Modrinth](https://modrinth.com/mod/utility-belt/version/1.3.2+1.19.2)

**Comment by booa12** [comment] 2023-06-21 09:55
Ok i will test it soon as i will go swiming

**Comment by booa12** [comment] 2023-06-21 09:55
Have a nice day

**Comment by booa12** [comment] 2023-06-21 10:05
made a natoer issue for not same error https://github.com/JamCoreModding/utility-belt/issues/28

**Comment by Jamalam360** [comment] 2023-06-21 11:16
So this issue is solved?

**Closed** 2023-06-21 11:34 UTC
